rivos: drivers: Fix qemu edu driver llvm build failure
pin_user_pages_fast expects an unsigned long, not a pointer, simply cast
to fix the following build failure:

../drivers/misc/qemu-edu.c:97:29: error: incompatible pointer to integer conversion passing 'const char *' to parameter of type 'unsigned long' [-Wint-conversion]
                ret = pin_user_pages_fast(buf, 1, FOLL_WRITE, pages);
                                          ^~~
../include/linux/mm.h:2384:39: note: passing argument to parameter 'start' here
int pin_user_pages_fast(unsigned long start, int nr_pages,
                                      ^
../drivers/misc/qemu-edu.c:149:29: error: incompatible pointer to integer conversion passing 'char *' to parameter of type 'unsigned long' [-Wint-conversion]
                ret = pin_user_pages_fast(buf, 1, 0, pages);
                                          ^~~
../include/linux/mm.h:2384:39: note: passing argument to parameter 'start' here
int pin_user_pages_fast(unsigned long start, int nr_pages,
                                      ^

Signed-off-by: Alexandre Ghiti <alexghiti@rivosinc.com>