RISC-V: selftests: cbo: Use exported __cpu_to_le32() with uapi header
cpu_to_le32 is not defined in uapi headers, and it could cause an error
of impossible constraint in 'asm' during compilation. However,
the reason is due to undefined reference to cpu_to_le32.
__cpu_to_le32() defined from byteorder.h should be used instead.

Signed-off-by: Hsieh-Tseng Shen <woodrow.shen@sifive.com>
Signed-off-by: Björn Töpel <bjorn@rivosinc.com>