perf syscalltbl: Add syscalltbl__id_at_idx() with no syscall table support
When HAVE_SYSCALL_TABLE_SUPPORT is not defined, neither is
syscalltbl__id_at_idx(). However, this function is expected to be
defined when HAVE_BPF_SKEL is defined.

Return -1 from syscalltbl__id_at_idx() to match the other functions when
HAVE_SYSCALL_TABLE_SUPPORT is not defined.

Without this, compiling perf on riscv when libtraceevents, libelf, and
clang are available will cause the functions trying to call
syscalltbl__id_at_idx() to be compiled. This results in the following
error:

/usr/bin/ld: perf-in.o: in function `.L0 ':
builtin-trace.c:(.text+0x60b14): undefined reference to `syscalltbl__id_at_idx'
/usr/bin/ld: builtin-trace.c:(.text+0x60c6c): undefined reference to `syscalltbl__id_at_idx'
/usr/bin/ld: perf-in.o: in function `.L2564':
builtin-trace.c:(.text+0x60cb6): undefined reference to `syscalltbl__id_at_idx'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile.perf:793: perf] Error 1
make[1]: *** [Makefile.perf:290: sub-make] Error 2
make: *** [Makefile:70: all] Error 2
make: Leaving directory '/src/linux-6.11-rc5/tools/perf'

This patch resolves this issue for all architectures which do not define
HAVE_SYSCALL_TABLE_SUPPORT.

$ ./perf trace -e syscalls:sys_enter_mmap --max-events=1 ls
0.000 ls/287 syscalls:sys_enter_mmap(__syscall_nr: 222, len: 9939, prot: READ, flags: PRIVATE, fd: 3)

Signed-off-by: Charlie Jenkins <charlie@rivosinc.com>
Reported-by: David Abdurachmanov <davidlt@rivosinc.com>
Suggested-by: David Abdurachmanov <davidlt@rivosinc.com>
Fixes: 7a2fb5619cc1 ("perf trace: Fix iteration of syscall ids in syscalltbl->entries")
Signed-off-by: Björn Töpel <bjorn@rivosinc.com>